services:
  php:
    environment:
      PHP_IDE_CONFIG: "serverName=admin.tracker.local"
    container_name: tracker_php
    build: ./deploy/docker/dev/php
    volumes:
      - ./:/var/www/tracker
      - ./deploy/docker/dev/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./deploy/docker/dev/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    working_dir: /var/www/tracker
    ports:
      - 9001:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      internal:
        ipv4_address: 192.168.222.3

  nginx:
    container_name: tracker_nginx
    build: deploy/docker/dev/nginx/build
    working_dir: /var/www/tracker
    volumes:
      - ./:/var/www/tracker
      - ./deploy/docker/dev/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8000:80
    networks:
      internal:
        ipv4_address: 192.168.222.4

  #  mysql:
  #    container_name: radar_mysql
  #    image: mysql:8.0
  #    working_dir: /var/www/radar
  #    restart: on-failure
  #    env_file:
  #      - ./deploy/docker/dev/mysql/.env
  #    volumes:
  #      - ./deploy/docker/dev/mysql/my.cnf:/etc/mysql/my.cnf
  #    networks:
  #      internal:
  #        ipv4_address: 192.168.222.2

  #  redis:
  #    image: redis
  #    container_name: radar_redis
  #    ports:
  #      - 6379:6379
  #    networks:
  #      internal:
  #        ipv4_address: 192.168.222.5

  frontend:
    container_name: tracker_front
    env_file:
      - ./frontend/.env.local
    build:
      context: ./frontend
      dockerfile: ../deploy/docker/dev/frontend/build/Dockerfile
    volumes:
      - ./frontend:/tracker
      - '/tracker/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      internal:
        ipv4_address: 192.168.222.6

volumes:
  mysql:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28
