nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']  # Укажите разрешенные источники
        allow_methods: ['GET', 'POST', 'OPTIONS']  # Укажите методы, которые разрешены
        allow_headers: ['Content-Type', 'Authorization']  # Укажите заголовки
        expose_headers: []
        max_age: 3600
        allow_credentials: true  # Измените supports_credentials на allow_credentials
    paths:
        '^/api/': # Указываем, что настройки действуют только для API
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            allow_credentials: true  # И здесь тоже
