ARG PHP_VERSION=7.4.33

RUN apt-get update && apt-get install -y \
    libicu-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip unzip git \
    && docker-php-ext-install \
    intl \
    json \
    ctype \
    iconv \
    bcmath \
    pdo pdo_mysql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2.3 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/symfony

COPY backend/composer.json backend/composer.lock /var/www/symfony/

RUN composer install --no-dev --optimize-autoloader --prefer-dist

COPY .. /var/www/symfony

RUN chown -R www-data:www-data /var/www/symfony

EXPOSE 9000

